#pragma once

#include <raylib.h>

#define DEFAULT_WINDOW_WIDTH 1280
#define DEFAULT_WINDOW_HEIGHT 720
#define WINDOW_TITLE "Breakout"
#define TARGET_FPS 60
#define WINDOW_FLAGS FLAG_WINDOW_RESIZABLE
#define WINDOW_BACKGROUND_COLOR BLACK
#define STARTING_ANGLE 0
#define STARTING_HEALTH 3
#define PLAYER_SCALE_FACTOR 20
#define PLAYER_COLOR WHITE
#define ASTEROID_SCALE_FACTOR 25
#define ASTEROID_COLOR RED
#define ASTEROID_SPAWN_TIME 3
#define KEY_PLAYER_MOVE_UP KEY_W
#define KEY_PLAYER_MOVE_DOWN KEY_S
#define KEY_PLAYER_MOVE_RIGHT KEY_D
#define KEY_PLAYER_MOVE_LEFT KEY_A
#define KEY_SHOOT KEY_SPACE
#define PLAYER_MOVEMENT_SPEED_FACTOR 5
#define ASTEROID_MOVEMENT_SPEED_FACTOR 10
#define PLAYER_GUN_COLOR RED
