#pragma once

#include <raylib.h>

#define DEFAULT_WINDOW_WIDTH 1280
#define DEFAULT_WINDOW_HEIGHT 720
#define WINDOW_TITLE "Breakout"
#define TARGET_FPS 60
#define WINDOW_FLAGS FLAG_WINDOW_RESIZABLE
#define WINDOW_BACKGROUND_COLOR BLACK
#define STARTING_ANGLE 0
#define STARTING_HEALTH 3
#define PLAYER_SCALE_FACTOR 20
#define PLAYER_COLOR WHITE
